### ISSUE TITLE
`orca` model name changed to `orca-mini`

### ISSUE THREAD

**Issue by myakura** [MassimilianoPasquini97/raycast_ollama#3]
per https://github.com/jmorganca/ollama/commit/d3b838ce603863c661ae4710a733b78d46d14ca8

**Comment by MassimilianoPasquini97** [comment]
Thank for your advice, I have updated README.md with the new model name https://github.com/MassimilianoPasquini97/raycast_ollama/commit/e3aecf526024b3d2fb2d57212f63fa876e32a0c9.
